version: '3.6'
services:
  selenoid:
    image: 'aerokube/selenoid:latest'
    container_name: selenoid
    ports:
      - '4444:4444'
    networks:
      - selenoid
    volumes:
      - './config/browsers.json:/etc/selenoid/browsers.json:ro'
      - './selenoid-outputs/output/:/output'
      - '/var/run/docker.sock:/var/run/docker.sock'
      - './selenoid-outputs/video:/opt/selenoid/video'
      - './selenoid-outputs/logs:/opt/selenoid/logs'
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=./selenoid-outputs/video
    command:
      - '-conf'
      - /etc/selenoid/browsers.json
      - '-video-output-dir'
      - /opt/selenoid/video
      - '-container-network'
      - selenoid
      - '-log-output-dir'
      - /opt/selenoid/logs
      - '-limit'
      - '5'
      - '-save-all-logs'
      - '-enable-file-upload'
  selenoid-video-recorder:
    image: 'selenoid/video-recorder:latest-release'
  selenoid-ui:
    image: 'aerokube/selenoid-ui'
    container_name: selenoid-ui
    links:
      - selenoid
    ports:
      - '8080:8080'
    networks:
      - selenoid
    command:
      - '--selenoid-uri'
      - 'http://selenoid:4444'
  chrome:
    image: 'selenoid/chrome:114.0'
    container_name: chrome
    links:
      - selenoid
      - selenoid-ui
    depends_on:
      - selenoid
      - selenoid-ui
    networks:
      - selenoid
    volumes:
      - '/dev/shm:/dev/shm'
  firefox:
    image: 'selenoid/firefox:115.0'
    container_name: firefox
    links:
      - selenoid
      - selenoid-ui
    depends_on:
      - selenoid
      - selenoid-ui
    networks:
      - selenoid
    volumes:
      - '/dev/shm:/dev/shm'
  android-chrome:
    image: 'selenoid/chrome-mobile:86.0'
    container_name: android-chrome
    links:
      - selenoid
      - selenoid-ui
    depends_on:
      - selenoid
      - selenoid-ui
    networks:
      - selenoid
    volumes:
      - '/dev/shm:/dev/shm'
networks:
  selenoid:
    name: selenoid
